name: Setup Kornia dev environment

inputs:
  python-version:
    description: "The python version desired."
    required: true
    default: "3.11"
    type: string

  pytorch-version:
    description: "The pytorch version desired."
    required: true
    default: "2.2.1"
    type: string

  ref:
    default: ${{ github.sha }}

  fetch-depth:
    default: 1

  extra-deps:
    description: "Dependencies to be installed manually before installing kornia."
    default: ""
    required: False
    type: strig

runs:
  using: "composite"
  steps:
    - uses: asottile/workflows/.github/actions/fast-checkout@v1.6.0
      with:
        repository: kornia/kornia
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Setup environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - if: ${{ contains(fromJson('["nightly"]'), inputs.pytorch-version ) }}
      name: Install PyTorch nightly
      shell: bash
      run: pip install numpy --pre torch[dynamo] ${{ inputs.extra-deps }} --force-reinstall --extra-index-url https://download.pytorch.org/whl/nightly/cpu/

    - if: ${{ contains(fromJson('["nightly"]'), inputs.pytorch-version ) == false}}
      name: Install pytorch
      shell: bash
      run: pip install torch==${{ inputs.pytorch-version }} ${{ inputs.extra-deps }} --index-url https://download.pytorch.org/whl/cpu

    - if: ${{ contains(fromJson('["1.9.1"]'), inputs.pytorch-version) }}
      name: Install accelerate for old torchs
      shell: bash
      run: pip install accelerate==0.20.3

    - name: Install Kornia dev
      shell: bash
      run: pip install .[dev,x]

    - name: Check torch version
      shell: bash
      run: pip show torch | grep ${{ inputs.pytorch-version }}  || false

    - name: Print dependencies and kornia version
      shell: bash
      run: |
        python -c "import torch;print('Pytorch version: ', torch.__version__)"
        python -c "import kornia;print('Kornia version: ', kornia.__version__)"
